// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CAARecordParser
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("raw_record")]
        public string RawRecord { get; set; }

        [JsonProperty("parsed")]
        public Parsed Parsed { get; set; }

        [JsonProperty("ca_info")]
        public CaInfo CaInfo { get; set; }

        [JsonProperty("interpretation")]
        public Interpretation Interpretation { get; set; }

        [JsonProperty("tag_description")]
        public string TagDescription { get; set; }

        [JsonProperty("is_valid")]
        public bool IsValid { get; set; }
    }

    public partial class CaInfo
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("wildcard_support")]
        public bool WildcardSupport { get; set; }
    }

    public partial class Interpretation
    {
        [JsonProperty("meaning")]
        public string Meaning { get; set; }

        [JsonProperty("restriction")]
        public string Restriction { get; set; }

        [JsonProperty("critical")]
        public bool Critical { get; set; }

        [JsonProperty("critical_explanation")]
        public string CriticalExplanation { get; set; }
    }

    public partial class Parsed
    {
        [JsonProperty("domain")]
        public string Domain { get; set; }

        [JsonProperty("ttl")]
        public long Ttl { get; set; }

        [JsonProperty("class")]
        public string Class { get; set; }

        [JsonProperty("flags")]
        public long Flags { get; set; }

        [JsonProperty("tag")]
        public string Tag { get; set; }

        [JsonProperty("value")]
        public string Value { get; set; }
    }
}
